name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ['ubuntu:20.04']
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build squid
        run: bash build.sh

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: /home/*.tgz
  
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: /home
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/home/*.tgz"
          tag: ${{ github.ref_name }}
