name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Docker command and get dynamic directory name
      id: docker_and_directory
      run: |
        # Ejecutar el comando Docker
        docker run --rm --name "zimbrabuild_ubuntu20" \
        -v ${{ github.workspace }}/volume:/home/git/BUILDS \
        -v ${{ github.workspace }}/ssh:/root/.ssh \
        -e BUILD_NO="0001" \
        -e BUILD_RELEASE="DAFFODIL" \
        -e BUILD_RELEASE_NO="10.0.6" \
        -e BUILD_OS="UBUNTU20_64" \
        -e BUILD_ARCH="amd64" \
        -e BUILD_TYPE="FOSS" \
        -e PKG_OS_TAG="u20" \
        -e BUILD_RELEASE_CANDIDATE="GA" \
        -e BUILD_THIRDPARTY_SERVER="files.zimbra.com" \
        -e INTERACTIVE="0" \
        docker.io/ovox/zimbrabuild-ubuntu20:latest

        # Obtener el nombre del directorio dinámico
        DIRECTORY_NAME=$(ls -td ${{ github.workspace }}/volume/*/ | head -n1)
        echo "$DIRECTORY_NAME"
        echo "$(ls -td $DIRECTORY_NAME*)"
        echo "directory_name=$DIRECTORY_NAME" >> "$GITHUB_ENV"      

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zimbra-package
        path: ${{ env.directory_name }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test artifact download 
        run: ls -R

      - name: Download packages
        id: download_packages
        uses: actions/download-artifact@v4
        with:
          name: zimbra-package

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ steps.download_packages.outputs.artifact_paths }}
          asset_name: zcs-10.0.6_GA_0001.UBUNTU20_64.tgz
          asset_content_type: application/zip